[package]
name = "conv"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "converter tool"
keywords = ["egui", "converter", "utility"]
readme = "README.md"
homepage = "https://github.com/phunks/conv"
repository = "https://github.com/phunks/conv"

#[profile.release]
#debug = true
#strip = "none"
#lto = "thin"
#codegen-units = 1
#split-debuginfo = "unpacked"


[dependencies]
env_logger = "0.11"
## see #7379, #1272
eframe = "0.31"
egui_extras = { version = "0.31", features = ["all_loaders"] }
strum = { version = "0.28", features = ["derive"] }
regex = { version = "1.13" }
fancy-regex = { version = "0.19.0" }
base64 = "0.23"
url-escape = "0.1"
html-escape = "0.2"
utf7-imap = "0.3"
flate2 = "1.1"
inflate = "0.4.5"
sha2 = { version = "0.11", default-features = false }
digest = { version = "0.11", features = ["alloc"] }
md5 = "0.8"
sha1 = "0.11"
base16ct = { version = "1.0", features = ["alloc"] }
aead = { version = "0.6", default-features = false }
aes-gcm = "0.11"
#html_parser = "0.7"
jaq-core = { version = "3.1" }
jaq-std  = { version = "3.0" }
jaq-json = { version = "2.0" }
codesnake = "=0.2.1"
unicode-width = "0.2"
bytes = "1.12.1"
